---
settings:
  displayErrorDetails: true
  db:
    driver: mysql
    host: localhost
    database: faculty
    username: root
    password: root
    charset: utf8
    collation: utf8_unicode_ci
    prefix:
